#!/usr/bin/python

from sys import argv
import os
from libxml import BuildXml
import random

VERSION = '1.0.3.2'
global destxml
if len(argv) == 1 :
    destxml = 'build.xml'
else:
    destxml = argv[1]
if destxml != '--' and 0 != destxml.find("--") :
    if len(argv) < 2 :
        print """Not enough parameters !
use --help for more informations"""
        exit(1)
    else:
        #
        if destxml[-4:] == '.xml':
            xml = BuildXml(argv[1])
            xml.getProject(0)
            dest = ""
            cmdline = "" 
            tmp = "/tmp/packjs_tmp_" + str( random.randint( 10000 , 100000 ) ) + ".js"
            # 
            if len(argv) >= 3 :
                if argv[2] == '--all' :
                    index = 0 
                    while True : 
                        xml.getTargetAt( xml.project , index )
                        index = index + 1 
                        if not xml.target :
                            exit();
                        else:
                            #print xml.target
                            #print argv[1]
                            os.system( ( "packjs-no %s %s") % ( argv[1] , xml.target ) )
                else:
                    cmdline = ("ant -buildfile %s %s") % (argv[1],argv[2])    
                    dest = argv[2]
            else:
                if not xml.target:
                    print "Error : xml file " + argv[1] + " have no target !"
                    exit(1)
                cmdline = ("ant -buildfile %s %s") % (argv[1],xml.target)
            #print cmdline
            result = os.system( cmdline )
            if result > 0 :
                exit(1)
            if not dest :
                dest = xml.target
            dest = xml.getDest( dest )
            #os.system( "mv " + dest + " " + tmp );
            #cmdline = ("mv %s %s") % (  tmp , dest )
            #result = os.system( cmdline )
            #if result > 0 :
               # os.system("rm .*.js  2>&1")
               # exit(1);
            #os.system( "mv " + tmp + " " + dest );
            #print cmdline
            #lib =  os.path.dirname(__file__) +  "/lib/yuicompressor-2.4.2.jar"
            #cmdline = ("java -jar %s --type js --charset utf-8 -o %s %s") % ( lib,desc,desc )
            #os.system( cmdline )
            print "done!"
else:
    global operation 
    operation = argv[1]
    if len(argv)>2 :
           operation = operation + argv[2]
    if operation == '--help' or operation == 'help':
        print "help information"
    elif operation == '--version' or operation == 'version':
        print ("PackJs version %s by darrel ") % (VERSION)
        os.system("ant -version")
    else:
        print ("Unknow operation %s \nuse --help for more information") % (operation)
        exit(1)
